### ISSUE TITLE
Remove should be confirmed

### ISSUE THREAD

**Issue by yugasun** [serverless-components/tencent-cos#5]
@pmuens After this [PR](https://github.com/serverless-components/tencent-cos/pull/3)，users can use any bucket which created before in cloud console. But there is a risk, when run `serverless remove` command, it will auto drop this bucket, even though there are other objects in this bucket.

So can we add a console dialog for comfirming deleteting operation? Like:

```
You will remove all objects in  bucket `xxx`, confirm?
```

**Comment by pmuens** [comment]
That's a good question. The problem is that Serverless Components should work in CI environments without any issues. Having a necessary prompt would break that flow.

We could add a flag like `serverless remove --confirm` so circumvent this.

I'm not sure how we handle that on the AWS side currently. Maybe we can start with a documentation around that behavior.

/cc @eahefnawy @ac360

**Comment by yugasun** [comment]
@pmuens I agree with your viewpoint, maybe we can indicate this in `README.md`, and let users know that _**they should be responsible for the remove operation**_.

**Comment by pmuens** [comment]
> @pmuens I agree with your viewpoint, maybe we can indicate this in README.md, and let users know that they should be responsible for the remove operation.

@yugasun yes, that sounds like a good, first step :+1:
